<?php
/**
 * Generated configuration constants for prod environment
 * DO NOT EDIT THIS FILE DIRECTLY
 */

define('GROCERSLIST_API_SUBDOMAIN', 'app');
define('GROCERSLIST_LINKSTA_SUBDOMAIN', '');
define('GROCERSLIST_EXTERNAL_JS_URL', 'https://app.grocerslist.com/wp-plugin.js'); 
